# Generated by Django 5.2.10 on 2026-02-05 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_projects_id_alter_task_id_alter_task_status_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='unique_pending_invite',
        ),
    ]
