services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: tododb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: L7062006v.
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    networks:
      - app_network

  backend:
    build:
      context: ./problems
      dockerfile: Dockerfile
    image: todo:latest
    container_name: backend
    env_file:
      - ./problems/problems/.env
    depends_on:
      - db
    expose:
      - "8000"
    ports:
      - "8000:8000"
    networks:
      - app_network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5000:5000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    expose:
      - "5000"
    networks:
      - app_network
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_network
  celery:
    image: todo:latest
    command: celery -A problems worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
    networks:
      - app_network

networks:
  app_network:
    name: app_network

volumes:
  pgdata: